# Generated by Django 5.2 on 2025-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='actionneurs',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='capteurs',
        ),
        migrations.AlterField(
            model_name='culture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Actionneur',
        ),
        migrations.DeleteModel(
            name='Capteur',
        ),
    ]
