# Generated by Django 5.2 on 2025-05-26 01:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_culture_actionneurs_remove_culture_capteurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='agriculteur',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='plante',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='lumiere',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='niveau_eau',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='humidite',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='mesure',
        ),
        migrations.AlterModelOptions(
            name='alerte',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='alerte',
            name='dashboard_a_type_pa_13fd02_idx',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='seuil_max',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='seuil_min',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='type_parametre',
        ),
        migrations.AddField(
            model_name='alerte',
            name='agriculteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='dashboard.agriculteur'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('humidity', 'Humidité'), ('ph', 'pH'), ('co2', 'CO2'), ('light', 'Lumière'), ('temperature', 'Température'), ('waterLevel', "Niveau d'eau")], default='humidity', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='message',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Intervalle',
        ),
        migrations.DeleteModel(
            name='Plante',
        ),
        migrations.DeleteModel(
            name='Mesure',
        ),
    ]
