# Generated by Django 5.2 on 2025-06-01 01:10

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_culture_agriculteur_remove_culture_plante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculteur',
            name='mqtt_token',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
    ]
